import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      initialRoute: '/',
      routes: {
        '/': (context) => SignInPage(),
        '/Profile': (context) => Profile(),
      },
    );
  }
}

class SignInPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 430,
          height: 932,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 19,
                top: 688,
                child: Container(
                  width: 393,
                  height: 73,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 25,
                        child: Container(
                          width: 393,
                          height: 48,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 270,
                                top: 0,
                                child: Container(
                                  width: 123,
                                  height: 48,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFFFEFEF),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 135,
                                top: 0,
                                child: Container(
                                  width: 123,
                                  height: 48,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFFFEFEF),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 123,
                                  height: 48,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFFFEFEF),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 48,
                        top: 35,
                        child: Container(
                          width: 345,
                          height: 33,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 269,
                                top: 0,
                                child: SizedBox(
                                  width: 76,
                                  height: 32,
                                  child: Text(
                                    'Sign In with\nMicrosoft',
                                    style: TextStyle(
                                      color: Color(0xFF553535),
                                      fontSize: 11,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 134,
                                top: 0,
                                child: SizedBox(
                                  width: 76,
                                  height: 32,
                                  child: Text(
                                    'Sign In with Facebook',
                                    style: TextStyle(
                                      color: Color(0xFF553535),
                                      fontSize: 11,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 1,
                                child: SizedBox(
                                  width: 76,
                                  height: 32,
                                  child: Text(
                                    'Sign In with Google',
                                    style: TextStyle(
                                      color: Color(0xFF553535),
                                      fontSize: 11,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 5,
                        top: 30,
                        child: Container(
                          width: 304,
                          height: 41,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 274,
                                top: 34,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://via.placeholder.com/30x30"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 137,
                                top: 3,
                                child: Container(
                                  width: 32,
                                  height: 32,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://via.placeholder.com/32x32"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 41,
                                  height: 41,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://via.placeholder.com/41x41"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 117,
                          height: 25,
                          child: Text(
                            'Others Options',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 15,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 466,
                child: Container(
                  width: 399,
                  height: 202,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 286,
                        top: 162,
                        child: GestureDetector(
                          onTap: () {
                            Navigator.pushNamed(context, '/Profile');
                          },
                          child: Container(
                            width: 112.56,
                            height: 39.55,
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 0,
                                  top: 0,
                                  child: Container(
                                    width: 112.56,
                                    height: 39.55,
                                    decoration: ShapeDecoration(
                                      color: Color(0xFF174295),
                                      shape: RoundedRectangleBorder(
                                        borderRadius:
                                        BorderRadius.circular(90.68),
                                      ),
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 34,
                                  top: 12,
                                  child: SizedBox(
                                    width: 44.55,
                                    height: 14.34,
                                    child: Text(
                                      'Log In',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 15,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                        height: 0,
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1,
                        top: 161,
                        child: Container(
                          width: 243,
                          height: 41,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 172,
                                top: 11,
                                child: SizedBox(
                                  width: 71,
                                  height: 20,
                                  child: Text(
                                    'Sign Up',
                                    style: TextStyle(
                                      color: Color(0xFF152D82),
                                      fontSize: 15,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w700,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 44,
                        child: Container(
                          width: 399,
                          height: 98,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 56,
                                child: Container(
                                  width: 399,
                                  height: 42,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFE0F0FF),
                                    shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(8)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 399,
                                  height: 42,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFE0F0FF),
                                    shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(8)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 12,
                                top: 12,
                                child: SizedBox(
                                  width: 121,
                                  height: 18,
                                  child: Text(
                                    'Email or Phone',
                                    style: TextStyle(
                                      color: Colors.black
                                          .withOpacity(0.5099999904632568),
                                      fontSize: 15,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 12,
                                top: 68,
                                child: SizedBox(
                                  width: 121,
                                  height: 18,
                                  child: Text(
                                    'Password',
                                    style: TextStyle(
                                      color: Colors.black
                                          .withOpacity(0.5099999904632568),
                                      fontSize: 15,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 3,
                        top: 0,
                        child: SizedBox(
                          width: 170,
                          height: 56,
                          child: Text(
                            'Sign In',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 24,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w100,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 3,
                        top: 172,
                        child: SizedBox(
                          width: 235,
                          height: 22,
                          child: Text(
                            'Don’t have an account?',
                            style: TextStyle(
                              color: Color(0xFF0C0B0B),
                              fontSize: 15,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 272,
                top: 396,
                child: SizedBox(
                  width: 149,
                  height: 38,
                  child: Text(
                    'Welcome',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 32,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w600,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -63,
                top: -24,
                child: Container(
                  width: 714,
                  height: 404,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image:
                      NetworkImage("https://via.placeholder.com/714x404"),
                      fit: BoxFit.fill,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(36.27),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 142,
                top: 919,
                child: Container(
                  width: 135,
                  height: 5,
                  decoration: ShapeDecoration(
                    color: Colors.black,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

class Profile extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 430,
          height: 932,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(30),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: -85,
                top: 374,
                child: Container(
                  width: 509,
                  height: 714,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 67,
                        top: 467,
                        child: Container(
                          width: 442,
                          height: 94,
                          decoration: BoxDecoration(color: Color(0xFFFFF5F5)),
                        ),
                      ),
                      Positioned(
                        left: 116,
                        top: 492,
                        child: Container(
                          width: 355.37,
                          height: 32.36,
                          child: Stack(children: []),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: -61,
                child: Container(
                  width: 445,
                  height: 350,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image:
                      NetworkImage("https://via.placeholder.com/445x350"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 90,
                child: SizedBox(
                  width: 249,
                  height: 60,
                  child: Text(
                    'Profile',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 48,
                      fontFamily: 'Sofia Sans',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 150,
                child: Container(
                  width: 395,
                  height: 121,
                  decoration: ShapeDecoration(
                    color: Color(0xFFE4FFFD),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 85,
                top: 161,
                child: Container(
                  width: 311,
                  height: 47,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 282,
                        top: 4,
                        child: Container(
                          width: 29,
                          height: 29,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage(
                                  "https://via.placeholder.com/29x29"),
                              fit: BoxFit.contain,
                            ),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                color: Colors.black.withOpacity(0),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 229,
                          height: 47,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: SizedBox(
                                  width: 229,
                                  height: 21,
                                  child: Text(
                                    'Catherine Rakkarnkin',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 21,
                                      fontFamily: 'Sofia Sans',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 26,
                                child: SizedBox(
                                  width: 229,
                                  height: 21,
                                  child: Text(
                                    'PLATINUM MEMBERSHIP | 15,000',
                                    style: TextStyle(
                                      color: Color(0xFF6A6363),
                                      fontSize: 15,
                                      fontFamily: 'Sofia Sans',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 215,
                child: Container(
                  width: 186,
                  height: 36,
                  decoration: BoxDecoration(color: Color(0xFFFFD8D8)),
                ),
              ),
              Positioned(
                left: 216,
                top: 215,
                child: Container(
                  width: 180,
                  height: 36,
                  decoration: BoxDecoration(color: Color(0xFFFFD8D8)),
                ),
              ),
              Positioned(
                left: 82,
                top: 222,
                child: SizedBox(
                  width: 95,
                  height: 23,
                  child: Text(
                    'Edit Profile',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 17,
                      fontFamily: 'Sofia Sans',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 253,
                top: 222,
                child: SizedBox(
                  width: 105,
                  height: 23,
                  child: Text(
                    'Point Reward',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 17,
                      fontFamily: 'Sofia Sans',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 443,
                child: Container(
                  width: 415,
                  height: 345,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(100),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 11,
                top: 304,
                child: Container(
                  width: 404,
                  height: 195,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 404,
                          height: 195,
                          decoration: ShapeDecoration(
                            color: Color(0xFFE7E6E6),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(15),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 10,
                        top: 15,
                        child: SizedBox(
                          width: 375,
                          height: 28,
                          child: Text(
                            'About Us',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 20,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 10,
                        top: 51,
                        child: SizedBox(
                          width: 375,
                          height: 28,
                          child: Text(
                            'Report Systems',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 20,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 10,
                        top: 87,
                        child: SizedBox(
                          width: 375,
                          height: 28,
                          child: Text(
                            'HiwKao Benefits',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 20,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 10,
                        top: 120,
                        child: SizedBox(
                          width: 375,
                          height: 28,
                          child: Text(
                            'Help',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 20,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 9,
                        top: 153,
                        child: SizedBox(
                          width: 375,
                          height: 28,
                          child: Text(
                            'HiwKao Privilege',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 20,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 21,
                top: 522,
                child: Container(
                  width: 389,
                  height: 295,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 91,
                        child: Container(
                          width: 389,
                          height: 44,
                          decoration: ShapeDecoration(
                            color: Color(0xFFA1F9F4),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 97,
                        top: 247,
                        child: Container(
                          width: 196,
                          height: 48,
                          decoration: ShapeDecoration(
                            color: Color(0xFFC23232),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 39,
                        child: Container(
                          width: 389,
                          height: 89,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 389,
                                  height: 44,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFA1F9F4),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 7,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  padding: const EdgeInsets.only(
                                    top: 2.50,
                                    left: 2.50,
                                    right: 2.50,
                                    bottom: 3.75,
                                  ),
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment:
                                    CrossAxisAlignment.center,
                                    children: [],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 54,
                                top: 10,
                                child: SizedBox(
                                  width: 207,
                                  height: 27,
                                  child: Text(
                                    'Your Favourites',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 18,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 53,
                                top: 62,
                                child: SizedBox(
                                  width: 207,
                                  height: 27,
                                  child: Text(
                                    'Privacy ',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 18,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 122,
                          height: 25,
                          child: Text(
                            'PINNED MENUS',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 17,
                              fontFamily: 'Sofia Sans',
                              fontWeight: FontWeight.w700,
                              height: 0.14,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 36,
                top: 623,
                child: Container(
                  width: 25,
                  height: 23,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 25,
                        height: 23,
                        child: Stack(children: []),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 177,
                top: 780,
                child: GestureDetector(
                  onTap: () {
                    Navigator.pushNamed(context, '/');
                  },
                  child: SizedBox(
                    width: 103,
                    height: 27,
                    child: Text(
                      'SIGN OUT',
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 20,
                        fontFamily: 'Inter',
                        fontWeight: FontWeight.w400,
                        height: 0,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 141,
                top: 778,
                child: Container(
                  width: 29,
                  height: 29,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/29x29"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
